### ISSUE TITLE
UDA challenge restriction

### ISSUE THREAD

**Issue by plana93** [epic-kitchens/C4-UDA-for-Action-Recognition#1]
Hi, I participated in the first phase of the Unsupervised Domain Adaptation challenge for Action Recognition and I would also be very happy to participate in this second one.
Unfortunately, the system doesn’t allow me because my total past submissions are greater than 50 ( according to the past rules). 

I see that in the second phase of the UDA challenge for Action Recognition, you've added a new restriction limiting the maximum number of submissions. My question is whether the submission counter is reset to zero for this part of the challenge or if it includes previous submissions, and in case if there is any chance to overcome this and have access to this second phase. In addition, I have multiple submissions that failed due to an initial issue in the source test .pkl file; why are these submissions included in the total submission counter?

**Comment by dimadamen** [comment]
When a new challenge/stage is opened next year, the total submissions is reset.
Yes, failed submissions count towards the total.
If you have issues with your account specifically, email us on: uob-epic-kitchens@bristol.ac.uk
